import "./globals.css";
import IRANSansXFaNum from "next/font/local";

const IRANSansFaNum = IRANSansXFaNum({
  src: [
    {
      path: "./fonts/IRANSansXFaNum-UltraLight.woff2",
      weight: "50",
      style: "ultralight",
    },
    {
      path: "./fonts/IRANSansXFaNum-Light.woff2",
      weight: "100",
      style: "light",
    },
    {
      path: "./fonts/IRANSansXFaNum-Thin.woff2",
      weight: "200",
      style: "thin",
    },
    {
      path: "./fonts/IRANSansXFaNum-Regular.woff2",
      weight: "300",
      style: "regular",
    },
    {
      path: "./fonts/IRANSansXFaNum-Medium.woff2",
      weight: "400",
      style: "medium",
    },
    {
      path: "./fonts/IRANSansXFaNum-DemiBold.woff2",
      weight: "500",
      style: "demiBold",
    },
    {
      path: "./fonts/IRANSansXFaNum-Bold.woff2",
      weight: "600",
      style: "bold",
    },
    {
      path: "./fonts/IRANSansXFaNum-ExtraBold.woff2",
      weight: "700",
      style: "extrabold",
    },
    {
      path: "./fonts/IRANSansXFaNum-Black.woff2",
      weight: "600",
      style: "blach",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body className={IRANSansFaNum.className}>
        <header className="flex flex-col justify-start items-center w-full h-min bg-transparent sticky top-0 border-2 border-solid border-zinc-800 ">
          <h1 className="sr-only">
            زیمانو - فروشگاه اینترنتی پخش لوازم و تجهیزات پزشکی و بهداشتی
          </h1>
          <div className="flex flex-row justify-center items-center gap-5 h-16 w-full bg-clip-padding backdrop-blur-sm bg-white/30 backdrop-brightness-95 backdrop-filter  back bg-white bg-opacity-5 ">
            <div className="flex flex-row justify-between items-center gap-5 h-12 w-full max-w-screen-2xl  ">
              <span
                role="link"
                className="flex-none block w-10 h-10 m-4 cursor-pointer"
              >
                <svg
                  width="40"
                  height="40"
                  viewBox="0 0 40 40"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M40 20C40 8.9559 31.0482 0 20 0C8.9559 0 0 8.9559 0 20C0 31.0441 8.9559 40 20 40C31.0441 40 40 31.0441 40 20ZM20.7994 31.5436L18.0374 34.2031L18.0353 34.199C17.8976 33.6388 17.0333 33.0803 15.3553 31.9959C15.1346 31.8533 14.8998 31.7016 14.6507 31.5395L11.103 34.9559C12.8384 35.7631 13.78 36.4667 14.6928 37.9026C15.2299 37.4079 15.7065 36.9859 16.1197 36.62L16.1203 36.6195L16.1204 36.6194C16.8241 35.9963 17.3441 35.5358 17.6671 35.1559C19.1389 35.8852 20.0005 36.5867 20.8374 37.9026C21.3737 37.4097 21.8496 36.9891 22.2624 36.6243C23.5583 35.4789 24.2327 34.8828 24.2018 34.3259C24.1683 33.7216 23.3043 33.1633 21.5029 31.9992L21.5029 31.9992L21.5024 31.9989C21.2822 31.8566 21.0479 31.7052 20.7994 31.5436ZM33.6464 9.74367C30.8946 11.8791 28.072 15.1796 26.6238 18.0637C39.8546 16.878 36.9038 28.1201 29.0915 31.476C23.3253 33.6544 18.8238 29.9129 19.1776 23.6811C19.2118 23.076 19.2676 22.4767 19.3448 21.8831C18.4341 24.2821 17.0966 26.6011 15.2843 28.8575C11.7887 33.2192 11.1485 32.6946 7.98895 30.1056L7.98888 30.1056C7.50795 29.7115 6.96864 29.2696 6.35201 28.7898C9.1038 26.6544 11.9264 23.3539 13.3746 20.4688C0.143805 21.6544 3.09457 10.4175 10.9069 7.05649C16.673 4.87905 21.1746 8.62059 20.8207 14.8514C20.7865 15.4551 20.7308 16.0544 20.6535 16.6493C21.5643 14.2493 22.9028 11.9314 24.7141 9.67495C28.2104 5.31231 28.851 5.83735 32.0118 8.42821C32.4921 8.82194 33.0307 9.26339 33.6464 9.74264V9.74367ZM21.8798 2.09996L18.3332 5.51637C20.0634 6.3297 21.006 7.02816 21.9188 8.45893C24.1379 6.41897 25.3234 5.61661 25.2827 4.88225C25.2451 4.20399 24.1614 3.58373 21.8798 2.09996Z"
                    fill="#00A2A2"
                  />
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M15.5071 16.3304C20.5481 3.82369 0.309129 17.5622 15.5071 16.3304Z"
                    fill="#00A2A2"
                  />
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24.4913 22.1951C39.6872 20.9633 19.4482 34.7018 24.4913 22.1951Z"
                    fill="#00A2A2"
                  />
                </svg>
              </span>

              <form className="grow">
                <label
                  htmlFor="default-search"
                  className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white"
                >
                  Search
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                    <svg
                      className="w-4 h-4 text-slate-500 "
                      aria-hidden="true"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 20 20"
                    >
                      <path
                        stroke="currentColor"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                      />
                    </svg>
                  </div>
                  <input
                    type="search"
                    id="default-search"
                    className="block w-96 p-3 pr-10 text-sm font-light text-zinc-900 border border-zinc-300 rounded-xl bg-slate-100 focus:outline-dashed focus:outline-1 focus:outline-slate-600 focus:outline-offset-2  focus:border-slate-500 placeholder-zinc-700"
                    placeholder="جست و جو محصول یا برند در زیمانو "
                    required
                  />
                  <button
                    type="submit"
                    className="sr-only absolute left-2.5 bottom-2.5 "
                  >
                    Search
                  </button>
                </div>
              </form>

              <div>
                <button>hole sale</button>
                <button>login</button>
              </div>

              <div>
                <span>Favorit</span>
                <span>Cart</span>
              </div>
            </div>
          </div>

          <nav
            aria-label="primary-navigation"
            className="flex flex-row justify-center items-center gap-5 w-full h-12  bg-cyan-500  "
          >
            <div className=" flex flex-row justify-between items-center w-full max-w-screen-2xl bg-violet-600">
              <ul className="flex flex-row justify-evenly items-start gap-5 m-1 font-light text-sm">
                <li>
                  <p>لوازم پزشکی </p>
                </li>
                <li>
                  <p>محصولات بهداشتی</p>
                </li>
                <li>
                  <p>دستگاه و لوازم</p>
                </li>
                <li>
                  <p>محصولات پوست و مو</p>
                </li>
                <li>
                  <p>خوراکی سلامت</p>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
