import "./globals.css";
import IRANSansXFaNum from "next/font/local";

const IRANSansFaNum = IRANSansXFaNum({
  src: [
    {
      path: "./fonts/IRANSansXFaNum-UltraLight.woff2",
      weight: "50",
      style: "ultralight",
    },
    {
      path: "./fonts/IRANSansXFaNum-Light.woff2",
      weight: "100",
      style: "light",
    },
    {
      path: "./fonts/IRANSansXFaNum-Thin.woff2",
      weight: "200",
      style: "thin",
    },
    {
      path: "./fonts/IRANSansXFaNum-Regular.woff2",
      weight: "300",
      style: "regular",
    },
    {
      path: "./fonts/IRANSansXFaNum-Medium.woff2",
      weight: "400",
      style: "medium",
    },
    {
      path: "./fonts/IRANSansXFaNum-DemiBold.woff2",
      weight: "500",
      style: "demiBold",
    },
    {
      path: "./fonts/IRANSansXFaNum-Bold.woff2",
      weight: "600",
      style: "bold",
    },
    {
      path: "./fonts/IRANSansXFaNum-ExtraBold.woff2",
      weight: "700",
      style: "extrabold",
    },
    {
      path: "./fonts/IRANSansXFaNum-Black.woff2",
      weight: "600",
      style: "blach",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body className={IRANSansFaNum.className}>
        <header className="flex flex-col justify-start items-center drop-shadow-zeemano-shadow-nav w-full h-min bg-transparent sticky top-0 ">
          <div className="flex flex-row justify-center items-center gap-5 h-16 w-full bg-slate-50 bg-clip-padding backdrop-filter backdrop-blur-md bg-opacity-70 backdrop-brightness-95 px-4 ">
            <div className="flex flex-row justify-between items-center gap-6 h-12 w-full max-w-screen-2xl  ">
              <span role="link" className="block w-10 h-10 m-4 cursor-pointer">
                <svg
                  width="40"
                  height="40"
                  viewBox="0 0 40 40"
                  fill="#00A2A2"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    clipRule="evenodd"
                    d="M40 20C40 8.9559 31.0482 0 20 0C8.9559 0 0 8.9559 0 20C0 31.0441 8.9559 40 20 40C31.0441 40 40 31.0441 40 20ZM20.7994 31.5436L18.0374 34.2031L18.0353 34.199C17.8976 33.6388 17.0333 33.0803 15.3553 31.9959C15.1346 31.8533 14.8998 31.7016 14.6507 31.5395L11.103 34.9559C12.8384 35.7631 13.78 36.4667 14.6928 37.9026C15.2299 37.4079 15.7065 36.9859 16.1197 36.62L16.1203 36.6195L16.1204 36.6194C16.8241 35.9963 17.3441 35.5358 17.6671 35.1559C19.1389 35.8852 20.0005 36.5867 20.8374 37.9026C21.3737 37.4097 21.8496 36.9891 22.2624 36.6243C23.5583 35.4789 24.2327 34.8828 24.2018 34.3259C24.1683 33.7216 23.3043 33.1633 21.5029 31.9992L21.5029 31.9992L21.5024 31.9989C21.2822 31.8566 21.0479 31.7052 20.7994 31.5436ZM33.6464 9.74367C30.8946 11.8791 28.072 15.1796 26.6238 18.0637C39.8546 16.878 36.9038 28.1201 29.0915 31.476C23.3253 33.6544 18.8238 29.9129 19.1776 23.6811C19.2118 23.076 19.2676 22.4767 19.3448 21.8831C18.4341 24.2821 17.0966 26.6011 15.2843 28.8575C11.7887 33.2192 11.1485 32.6946 7.98895 30.1056L7.98888 30.1056C7.50795 29.7115 6.96864 29.2696 6.35201 28.7898C9.1038 26.6544 11.9264 23.3539 13.3746 20.4688C0.143805 21.6544 3.09457 10.4175 10.9069 7.05649C16.673 4.87905 21.1746 8.62059 20.8207 14.8514C20.7865 15.4551 20.7308 16.0544 20.6535 16.6493C21.5643 14.2493 22.9028 11.9314 24.7141 9.67495C28.2104 5.31231 28.851 5.83735 32.0118 8.42821C32.4921 8.82194 33.0307 9.26339 33.6464 9.74264V9.74367ZM21.8798 2.09996L18.3332 5.51637C20.0634 6.3297 21.006 7.02816 21.9188 8.45893C24.1379 6.41897 25.3234 5.61661 25.2827 4.88225C25.2451 4.20399 24.1614 3.58373 21.8798 2.09996Z"
                  />
                  <path
                    fillRule="evenodd"
                    clipRule="evenodd"
                    d="M15.5071 16.3304C20.5481 3.82369 0.309129 17.5622 15.5071 16.3304Z"
                  />
                  <path
                    fillRule="evenodd"
                    clipRule="evenodd"
                    d="M24.4913 22.1951C39.6872 20.9633 19.4482 34.7018 24.4913 22.1951Z"
                  />
                </svg>
              </span>

              <form className="grow">
                <label
                  htmlFor="default-search"
                  className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white"
                >
                  Search
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                    <svg
                      className="w-4 h-4 text-slate-600 "
                      aria-hidden="true"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 20 20"
                    >
                      <path
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                      />
                    </svg>
                  </div>
                  <input
                    type="search"
                    id="default-search"
                    className=" flex flex-row justify-end gap-4 items-center w-96 h-10 p-3 pr-10 appearance-none text-sm font-light text-zinc-900 bg-slate-100 focus:outline-dashed focus:outline-1 focus:outline-slate-600 focus:outline-offset-2  focus:border-slate-500 placeholder-zinc-700 border border-zinc-300 rounded-xl"
                    placeholder="جست و جو محصول یا برند در زیمانو "
                    required
                  />

                  <button
                    type="submit"
                    className="sr-only absolute left-2.5 bottom-2.5 "
                  >
                    Search
                  </button>
                </div>
              </form>
              <button className="flex items-center justify-center h-10 bg-gradient-to-r p-[1px] from-zeemano-500 via-zeemano-600 to-zeemano-auxiliary-green rounded-lg">
                <div className="flex items-center justify-center h-full w-full  bg-white back rounded-[7px]">
                  <p className="text-center whitespace-nowrap text-sm font-normal text-zeemano-700 px-4">
                    درخواست خرید عمده
                  </p>
                </div>
              </button>

              <button className="flex flex-row justify-center items-center gap-3 h-10 w-max px-4 bg-white border-[1.6px] border-solid border-zinc-300 rounded-lg">
                <div className="flex flex-row justify-center items-center text-slate-600 text-center whitespace-nowrap text-sm font-normal">
                  <svg fill="none" width="24" height="24" viewBox="0 0 24 24">
                    <path
                      d="M16.2222 6.44444C16.2222 7.62318 15.754 8.75365 14.9205 9.58714C14.087 10.4206 12.9565 10.8889 11.7778 10.8889C10.599 10.8889 9.46858 10.4206 8.63508 9.58714C7.80159 8.75365 7.33333 7.62318 7.33333 6.44444C7.33333 5.2657 7.80159 4.13524 8.63508 3.30175C9.46858 2.46825 10.599 2 11.7778 2C12.9565 2 14.087 2.46825 14.9205 3.30175C15.754 4.13524 16.2222 5.2657 16.2222 6.44444ZM11.7778 14.2222C9.71498 14.2222 7.73667 15.0417 6.27806 16.5003C4.81944 17.9589 4 19.9372 4 22H19.5556C19.5556 19.9372 18.7361 17.9589 17.2775 16.5003C15.8189 15.0417 13.8406 14.2222 11.7778 14.2222Z"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="stroke-slate-600"
                    />
                  </svg>
                  <p className="flex flex-row justify-center items-center px-2 ">
                    ورود
                  </p>
                  <p className=" block px-2  border-r border-zinc-200">
                    ثبت نام
                  </p>
                </div>
              </button>

              <div className="flex flex-row justify-center items-center gap-4 w-24 h-10 ">
                <div>
                  <div className="relative block w-6">
                    <span role="button" className="w-6 h-6 block">
                      <svg
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        className="stroke-zeemano-500"
                        fill="none"
                      >
                        <path
                          d="M6 4.22222C6 3.63285 6.18061 3.06762 6.5021 2.65087C6.82359 2.23413 7.25963 2 7.71429 2H16.2857C16.7404 2 17.1764 2.23413 17.4979 2.65087C17.8194 3.06762 18 3.63285 18 4.22222V22L12 18.1111L6 22V4.22222Z"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </span>
                    <span className="absolute inline-flex items-center justify-center p-1 text-white bg-red-500 -top-3 -right-3 w-max min-w-[24px] h-6 border-2 border-solid border-slate-50 rounded-full">
                      <p className="font-normal text-xs text-white">99</p>
                    </span>
                  </div>
                </div>

                <hr className="w-[2px] h-6 bg-slate-300 mx-auto"></hr>

                <div>
                  <div className="relative block w-6">
                    <span role="button" className="w-6 h-6 block">
                      <svg
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        className="stroke-zeemano-500"
                        fill="none"
                      >
                        <path
                          d="M16.3333 10.8889V6.44444C16.3333 5.2657 15.8651 4.13524 15.0316 3.30175C14.1981 2.46825 13.0676 2 11.8889 2C10.7101 2 9.57969 2.46825 8.74619 3.30175C7.9127 4.13524 7.44444 5.2657 7.44444 6.44444V10.8889M4.11111 8.66667H19.6667L20.7778 22H3L4.11111 8.66667Z"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </span>
                    <span className="absolute inline-flex items-center justify-center p-1 text-white bg-red-500 -top-3 -right-3 w-max min-w-[24px] h-6 border-2 border-solid border-slate-50 rounded-full">
                      <p className="font-normal text-xs text-white">99</p>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <h1 className="sr-only">
            زیمانو - فروشگاه اینترنتی پخش لوازم و تجهیزات پزشکی و بهداشتی
          </h1>

          <nav
            aria-label="primary-navigation"
            className="flex flex-row justify-center items-center w-full h-10 bg-slate-50  "
          >
            <div className=" flex flex-row justify-start items-center w-full gap-5 max-w-screen-2xl px-4">
              <p className="whitespace-nowrap text-xs  text-zeemano-500 ">
                تجهیزات پزشکی زیمانو{" "}
              </p>

              <ul className="flex flex-row justify-start items-center gap-5 m-1 font-light text-sm grow">
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-2 w-max h-6 text-slate-600  "
                  >
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      className="stroke-slate-700"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M2 5H22M2 12.5H22M2 20H22"
                        strokeWidth="1.6"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                    <p className="text-sm text-slate-700 ">لوازم پزشکی</p>
                  </button>

                  <div
                    id="dropdownNavbar"
                    className="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                  >
                    <ul
                      className="py-2 text-sm text-gray-700 dark:text-gray-400"
                      aria-labelledby="dropdownLargeButton"
                    >
                      <li>
                        <a
                          href="#"
                          className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                        >
                          Dashboard
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                        >
                          Settings
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                        >
                          Earnings
                        </a>
                      </li>
                    </ul>
                    <div className="py-1">
                      <a
                        href="#"
                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
                      >
                        Sign out
                      </a>
                    </div>
                  </div>
                </li>

                <hr className="w-[2px] h-6 bg-slate-300 mx-2"></hr>

                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <p className="text-sm text-center whitespace-nowrap text-slate-700 ">
                      لوازم پزشکی
                    </p>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      className="stroke-slate-700 scale-50"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M22 7L12 17L2 7"
                        strokeWidth="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </button>
                </li>
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <p className="text-sm text-center whitespace-nowrap text-slate-700 ">
                      محصولات بهداشتی{" "}
                    </p>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      className="stroke-slate-700 scale-50"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M22 7L12 17L2 7"
                        strokeWidth="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </button>
                </li>
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <p className="text-sm text-center whitespace-nowrap text-slate-700 ">
                      دستگاه و لوازم
                    </p>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      className="stroke-slate-700 scale-50"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M22 7L12 17L2 7"
                        strokeWidth="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </button>
                </li>
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <p className="text-sm text-center whitespace-nowrap text-slate-700 ">
                      محصولات پوست و مو
                    </p>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      className="stroke-slate-700 scale-50"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M22 7L12 17L2 7"
                        strokeWidth="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </button>
                </li>
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <p className=" text-sm text-center whitespace-nowrap text-slate-700 ">
                      خوراکی سلامت
                    </p>
                  </button>
                </li>
                <li>
                  <button
                    id="dropdownNavbarLink"
                    data-dropdown-toggle="dropdownNavbar"
                    className="flex items-center justify-center gap-1 w-full h-6 text-slate-600  "
                  >
                    <svg
                      width="40"
                      height="40"
                      viewBox="0 0 40 40"
                      className="stroke-slate-700 scale-75"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M29.9626 14.5039L22.7744 24.9326"
                        strokeWidth="1.6"
                        strokeMiterlimit="10"
                        strokeLinecap="round"
                      />
                      <path
                        d="M23.1529 18.1207C24.1278 18.1207 24.918 17.3304 24.918 16.3555C24.918 15.3806 24.1278 14.5903 23.1529 14.5903C22.178 14.5903 21.3877 15.3806 21.3877 16.3555C21.3877 17.3304 22.178 18.1207 23.1529 18.1207Z"
                        strokeMiterlimit="10"
                        strokeLinecap="round"
                        strokeWidth="1.6"
                      />
                      <path
                        d="M31.3494 23.0806C31.3494 24.0556 30.5579 24.8472 29.5791 24.8472C28.604 24.8472 27.8125 24.0556 27.8125 23.0806C27.8125 22.1055 28.604 21.3149 29.5791 21.3149C30.5584 21.3149 31.3494 22.1051 31.3494 23.0806Z"
                        strokeMiterlimit="10"
                        strokeLinecap="round"
                        strokeWidth="1.6"
                      />
                      <path
                        d="M17.5784 10.24V16.24H11.696L17.2254 10H33.8475C34.624 10 35.2593 10.6353 35.2593 11.4118V28.0254C35.2593 28.8009 34.624 29.4372 33.8475 29.4372H5.41176C4.63529 29.4372 4 28.8009 4 28.0254V11.4118C4 10.6353 4.63529 10 5.41176 10H11.5784V12.7106"
                        strokeMiterlimit="10"
                        strokeLinejoin="round"
                        strokeWidth="1.6"
                      />
                      <path
                        d="M11.6611 18.4707V20.9658"
                        strokeMiterlimit="10"
                        strokeLinejoin="round"
                        strokeWidth="1.6"
                      />
                      <path
                        d="M11.6611 22.6636V25.1591"
                        strokeMiterlimit="10"
                        strokeLinejoin="round"
                        strokeWidth="1.6"
                      />
                      <path
                        d="M11.6611 26.8564V29.3581"
                        strokeMiterlimit="10"
                        strokeLinejoin="round"
                        strokeWidth="1.6"
                      />
                    </svg>
                    <p className=" text-sm text-center whitespace-nowrap text-slate-700 ">
                      تخفیف ویژه
                    </p>
                  </button>
                </li>
              </ul>

              <div className="flex flex-row justify-between items-center gap-4 ">
                <p className="text-center whitespace-nowrap text-xs text-slate-700">
                  زیمانو پلاس
                </p>

                <hr className="w-[2px] h-6 bg-slate-300 mx-auto"></hr>

                <p className="text-center whitespace-nowrap text-xs text-slate-700">
                  مجله زیمانو
                </p>
              </div>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
