import Header from "@/components/navigation-bar/header";
import Footer from "@/components/footer/primary-footer";
import SecondaryFooter from "@/components/footer/secondary-footer";
import "./globals.css";
import IRANSansXFaNum from "next/font/local";

const IRANSansFaNum = IRANSansXFaNum({
  src: [
    {
      path: "../../public/fonts/IRANSansXFaNum-UltraLight.woff2",
      weight: "50",
      style: "ultralight",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Light.woff2",
      weight: "100",
      style: "light",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Thin.woff2",
      weight: "200",
      style: "thin",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Regular.woff2",
      weight: "300",
      style: "regular",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Medium.woff2",
      weight: "400",
      style: "medium",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-DemiBold.woff2",
      weight: "500",
      style: "demiBold",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Bold.woff2",
      weight: "600",
      style: "bold",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-ExtraBold.woff2",
      weight: "700",
      style: "extrabold",
    },
    {
      path: "../../public/fonts/IRANSansXFaNum-Black.woff2",
      weight: "600",
      style: "blach",
    },
  ],
});

export const metadata = {
  title: "سامانه آنلاین پخش تجهیزات پزشکی و لوازم بهداشتی زیمانو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body className={IRANSansFaNum.className}>
        <Header />
        {children}
        {/* <SecondaryFooter/>
        <Footer/> */}
      </body>
    </html>
  );
}
